name: Lint code

on: push

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
